"""`damso-server` entrypoint: runs the HTTP daemon via uvicorn.

The server always speaks plain HTTP (ADR 0003). A loopback bind needs no
credentials at all - the client and server are the same trust boundary
already (D-08). Any other bind requires the bearer token generated by
`make install-server` / `damso-server-credentials generate`, and relies on
the operator's trusted private network (Tailscale or a trusted LAN) for
transport privacy instead of app-level TLS.
"""

from __future__ import annotations

import argparse
import sys

import uvicorn

from .app import create_app
from .config import ServerConfig
from .credentials import CredentialsMissing, load as load_credentials


def main() -> int:
    parser = argparse.ArgumentParser(description="Damso HTTP server (canonical store owner)")
    parser.add_argument("--store", help="canonical store root (overrides DAMSO_STORE)")
    parser.add_argument("--host", help="bind host (overrides DAMSO_SERVER_HOST, default 127.0.0.1)")
    parser.add_argument("--port", type=int, help="bind port (overrides DAMSO_SERVER_PORT)")
    arguments = parser.parse_args()

    import os

    environment = dict(os.environ)
    if arguments.store:
        environment["DAMSO_STORE"] = arguments.store
    if arguments.host:
        environment["DAMSO_SERVER_HOST"] = arguments.host
    if arguments.port:
        environment["DAMSO_SERVER_PORT"] = str(arguments.port)

    config = ServerConfig.from_environment(environment)
    app = create_app(config)

    if not config.loopback_only:
        try:
            load_credentials(config.credentials_dir)
        except CredentialsMissing as error:
            print(str(error), file=sys.stderr)
            return 1

    uvicorn.run(app, host=config.host, port=config.port, log_level="info")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
